# Generated by Django 2.1.5 on 2019-02-12 13:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='haras',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='client',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cicloestral',
            name='egua',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Animal'),
        ),
        migrations.AddField(
            model_name='animal',
            name='allocation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Haras', verbose_name='Locação'),
        ),
        migrations.AddField(
            model_name='animal',
            name='ancillary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Ancillary', verbose_name='Auxiliar'),
        ),
        migrations.AddField(
            model_name='animal',
            name='proprietary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Client', verbose_name='Proprietário'),
        ),
        migrations.AddField(
            model_name='animal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ancillary',
            name='haras',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Haras'),
        ),
        migrations.AddField(
            model_name='ancillary',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
