# Generated by Django 2.1.5 on 2019-02-28 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cicloestral',
            name='date',
            field=models.DateField(default='28/02/2019', verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='cicloestral',
            name='description',
            field=models.TextField(verbose_name='Descrição'),
        ),
    ]
