# Generated by Django 2.1.5 on 2019-04-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190401_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cicloestral',
            name='date',
            field=models.DateField(default='03/04/2019', verbose_name='Data'),
        ),
    ]
