# Generated by Django 2.1.5 on 2019-04-05 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20190403_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cicloestral',
            name='date',
            field=models.DateField(default='05/04/2019', verbose_name='Data'),
        ),
    ]
